language: node_js
node_js:
- stable
notifications:
  email: true
  slack: webhouseteam:82qu1PX5R5wkYNCW5x6fVlhu
script:
- yarn
- yarn build
- cp ./build/index.html ./build/200.html
deploy:
  provider: surge
  project: "./build/"
  domain: odeumcodeapp.surge.sh
  skip_cleanup: true
  on:
    all_branches: true
before_install:
- openssl aes-256-cbc -K $encrypted_596e0b1891ad_key -iv $encrypted_596e0b1891ad_iv
  -in deploy_rsa.enc -out deploy_rsa -d
